//! Embeds the migration set at compile time.
//!
//! This is the stand-in for `sqlx::migrate!`, whose proc macro lives behind
//! sqlx's `macros` feature — and enabling that feature here would turn it on for
//! every crate in a consumer's build through feature unification, quietly
//! re-arming the compile-time query macros in projects that deliberately retired
//! them. A build script costs nothing and keeps zurid's sqlx surface to
//! `derive`.
//!
//! It writes `embedded_migrations.rs` into `OUT_DIR`: a sorted static array of
//! `(version, description, sql)` that [`zurid::postgres::migrator`] turns into
//! the same `sqlx::migrate::Migrator` the macro would have expanded to. The
//! checksums match sqlx's own directory resolver (`Migration::new` hashes the
//! same SQL text), so a `_sqlx_migrations` ledger written by the sqlx CLI stays
//! valid.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    let migrations = manifest.join("migrations");
    println!("cargo:rerun-if-changed={}", migrations.display());

    let mut files: Vec<PathBuf> = fs::read_dir(&migrations)
        .expect("the migrations directory exists")
        .map(|entry| entry.expect("a readable directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "sql"))
        .collect();
    // sqlx orders migrations by the leading version; lexicographic filename
    // order is identical because the prefix is fixed-width.
    files.sort();

    let mut generated = String::from(
        "/// Generated by build.rs from `migrations/` — do not edit.\n\
         static EMBEDDED_MIGRATIONS: &[(i64, &str, &str)] = &[\n",
    );
    for file in &files {
        let stem = file
            .file_stem()
            .expect("a .sql file stem")
            .to_string_lossy();
        let (version, name) = stem
            .split_once('_')
            .expect("migration files are named <version>_<name>.sql");
        assert!(
            version.chars().all(|c| c.is_ascii_digit()),
            "a migration version prefix must be numeric: {stem}"
        );
        // Match sqlx's directory resolver: the description is the filename
        // remainder with underscores read as spaces.
        let description = name.replace('_', " ");
        let relative = format!(
            "/migrations/{}",
            file.file_name()
                .expect("a migration file name")
                .to_string_lossy()
        );
        generated.push_str(&format!(
            "    ({version}, {description:?}, \
             include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {relative:?}))),\n"
        ));
    }
    generated.push_str("];\n");

    let destination =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_migrations.rs");
    fs::write(destination, generated).expect("write embedded_migrations.rs");
}
